src/Curtis/AppBundle/Entity/LocalityRegion.php
<?php
namespace Curtis\AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Locality
 *
 * @package Curtis\AppBundle\Entity
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks()
 */
class LocalityRegion
{
    use DateCreateUpdateTrait;

    /**
     * @var integer
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=80, nullable=false)
     */
    private $name;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $photo;

    /**
     * @var LocalityStateArea
     * @ORM\ManyToOne(targetEntity="Curtis\AppBundle\Entity\LocalityStateArea", inversedBy="regions")
     */
    private $stateArea;

    /**
     * @var LocalityPlace
     * @ORM\OneToMany(targetEntity="Curtis\AppBundle\Entity\LocalityPlace", mappedBy="region")
     */
    private $places;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->places = new ArrayCollection();
    }

    /**
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getUnlockedPlaces()
    {
        $criteria = Criteria::create();
        $criteria->andWhere(Criteria::expr()->eq('isLocked', false));
        return $this->places->matching($criteria);
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return LocalityRegion
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get photo
     *
     * @return string
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * Set photo
     *
     * @param string $photo
     *
     * @return LocalityRegion
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return LocalityRegion
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return LocalityRegion
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Get stateArea
     *
     * @return LocalityStateArea
     */
    public function getStateArea()
    {
        return $this->stateArea;
    }

    /**
     * Set stateArea
     *
     * @param LocalityStateArea $stateArea
     *
     * @return LocalityRegion
     */
    public function setStateArea(LocalityStateArea $stateArea = null)
    {
        $this->stateArea = $stateArea;

        return $this;
    }

    /**
     * Add place
     *
     * @param LocalityPlace $place
     *
     * @return LocalityRegion
     */
    public function addPlace(LocalityPlace $place)
    {
        $this->places[] = $place;

        return $this;
    }

    /**
     * Remove place
     *
     * @param LocalityPlace $place
     */
    public function removePlace(LocalityPlace $place)
    {
        $this->places->removeElement($place);
    }

    /**
     * Get places
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPlaces()
    {
        return $this->places;
    }
}

src/Curtis/AppBundle/Controller/LocalityController.php
<?php

namespace Curtis\AppBundle\Controller;

use Curtis\AppBundle\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class LocalityController extends Controller
{
    /**
     * @Route("/lokalita", name="locality-overview")
     */
    public function indexAction()
    {
        return $this->render('@CurtisApp/Locality/index.html.twig');
    }

    /**
     * @param $stateArea
     *
     * @Route("/lokalita/{stateArea}", name="locality-state-area")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function stateAreaAction($stateArea)
    {
        $stateArea = $this->getDoctrine()->getRepository(Entity\LocalityStateArea::class)->findByUrlKey($stateArea);
        if (!$stateArea) {
            throw $this->createNotFoundException();
        }

        return $this->render('@CurtisApp/Locality/state-area.html.twig', [
            'stateArea' => $stateArea,
        ]);
    }

    /**
     * @param $regionId
     *
     * @Route("/lokalita/region/{regionId}", name="locality-region")
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function regionAction($regionId)
    {
        $region = $this->getDoctrine()->getRepository(Entity\LocalityRegion::class)->find($regionId);
        if (!$region) {
            throw $this->createNotFoundException();
        }

        return $this->render('@CurtisApp/Locality/region.html.twig', [
            'region' => $region,
        ]);
    }


    /**
     * @Route("/lokalita/miesto/{id}", name="locality-place")
     * @ParamConverter("place", class="CurtisAppBundle:LocalityPlace")
     * @param Entity\LocalityPlace $place
     *
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \LogicException
     */
    public function placeAction(Entity\LocalityPlace $place)
    {
        $template = '@CurtisApp/Locality/place.html.twig';
        if ($place->getIsLocked() && !$this->isGranted('ROLE_ADMIN')) {
            $template = '@CurtisApp/Locality/empty-place.html.twig';
        }

        return $this->render($template, [
            'place' => $place,
        ]);
    }
}

src/Curtis/AppBundle/Resources/views/Locality/empty-place.html.twig
{% extends '@CurtisTemplate/Layout/base-right-side.html.twig' %}


{% block breadcrumbs %}
    <header class="main-header">
        <div class="container">
            <h1 class="page-title">Lokality</h1>

            <ol class="breadcrumb pull-right">
                <li>
                    <a href="{{ url('locality-state-area', {'stateArea': place.region.stateArea.urlKey }) }}">{{ place.region.stateArea.name }}</a>
                </li>
                <li>
                    <a href="{{ url('locality-region', {'regionId': place.region.id }) }}">{{ place.region.name }}</a>
                </li>
                <li class="active">{{ place.name|raw }}</li>
            </ol>
        </div>
    </header>
{% endblock %}

{% block body %}
    <section>
        <div data-editable data-name="name">
            <h2 class="page-header no-margin-top">{{ place.name }}</h2>
        </div>
    </section>
{% endblock %}

{% block sidebar %}
    <div class="block animated fadeInDown animation-delay-10">
        <ul class="nav nav-tabs nav-tabs-ar" id="myTab2">
            <li class="active"><a href="#categories" data-toggle="tab"><i class="fa fa-folder-open"></i></a></li>
            {#<li><a href="#tags" data-toggle="tab"><i class="fa fa-tags"></i></a></li>#}
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="categories">
                <h3 class="post-title no-margin-top">Stolice (Župy)</h3>
                <ul class="simple">
                    {% for globalRegion in place.region.stateArea.regions %}
                        <li>
                            <a href="{{ url('locality-region', {'regionId': globalRegion.id }) }}">{{ globalRegion.name }}</a>
                            {% if globalRegion.id == place.region.id %}
                                <ul>
                                    {% for globalPlace in globalRegion.places %}
                                        <li>
                                            <a {% if globalPlace.id == place.id %}class="active"{% endif %}
                                               href="{{ url('locality-place', {'id': globalPlace.id}) }}">
                                                {% if globalPlace.id == place.id %}
                                                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                                                {% endif %}
                                                {% if globalPlace.isLocked %}
                                                    <i class="fa fa-lock" aria-hidden="true"></i>
                                                {% endif %}
                                                {{ globalPlace.name|raw }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>

            {#<div class="tab-pane" id="tags">#}
            {#<h3 class="post-title">Tags</h3>#}
            {#<div class="tags-cloud">#}
            {#<a href="#" class="tag">Web</a>#}
            {#<a href="#" class="tag">Artificial Intelligence</a>#}
            {#<a href="#" class="tag">Programing</a>#}
            {#<a href="#" class="tag">Design</a>#}
            {#<a href="#" class="tag">3D</a>#}
            {#<a href="#" class="tag">Games</a>#}
            {#<a href="#" class="tag">Resources</a>#}
            {#<a href="#" class="tag">2D</a>#}
            {#<a href="#" class="tag">C++</a>#}
            {#<a href="#" class="tag">Jquery</a>#}
            {#<a href="#" class="tag">Javascript</a>#}
            {#<a href="#" class="tag">Library</a>#}
            {#<a href="#" class="tag">Windows</a>#}
            {#<a href="#" class="tag">Linux</a>#}
            {#<a href="#" class="tag">Cloud</a>#}
            {#<a href="#" class="tag">Game developer</a>#}
            {#<a href="#" class="tag">Server</a>#}
            {#<a href="#" class="tag">Google</a>#}
            {#<a href="#" class="tag">Bootstrap</a>#}
            {#<a href="#" class="tag">Less</a>#}
            {#<a href="#" class="tag">Sass</a>#}
            {#<a href="#" class="tag">Engine</a>#}
            {#<a href="#" class="tag">Node.js</a>#}
            {#</div>#}
            {#</div>#}
        </div> <!-- tab-content -->
    </div>
{% endblock %}

src/Curtis/AppBundle/Resources/views/Locality/index.html.twig
{% extends '@CurtisTemplate/Layout/base.html.twig' %}

{% block breadcrumbs %}
    <header class="main-header">
        <div class="container">
            <h1 class="page-title">Slovensko</h1>

            {#<ol class="breadcrumb pull-right">#}
                {#<li><a href="#"></a></li>#}
                {#<li class="active"></li>#}
            {#</ol>#}
        </div>
    </header>
{% endblock %}

{% block body %}
    <iframe style="width:1100px;height:800px;" src="https://www.google.com/maps/d/embed?mid=1KyPQrPJ-64PvFq1_yaxoWuVkRSQ"></iframe>
{% endblock %}

src/Curtis/AppBundle/Resources/views/Locality/place.html.twig
{% extends '@CurtisTemplate/Layout/base-right-side.html.twig' %}


{% block stylesheet %}
    <style>
        [data-editable] iframe,
        [data-editable] image,
        [data-editable] [data-ce-tag=img],
        [data-editable] img,
        [data-editable] video {
            clear: both;
            display: block;
            margin-left: auto;
            margin-right: auto;
            max-width: 100%;
        }

        /* Left align */
        [data-editable] .align-left {
            clear: initial;
            float: left;
            margin-right: 0.5em;
        }

        /* Right align */
        [data-editable] .align-right {
            clear: initial;
            float: right;
            margin-left: 0.5em;
        }

        /* Alignment styles for text in editable regions */
        [data-editable] .text-center {
            text-align: center;
        }

        [data-editable] .text-left {
            text-align: left;
        }

        [data-editable] .text-right {
            text-align: right;
        }
    </style>
{% endblock %}

{% block breadcrumbs %}
    <header class="main-header">
        <div class="container">
            <h1 class="page-title">Lokality</h1>

            {% if is_granted("ROLE_ADMIN") %}
                <a href="{{ path('admin-locality-create-place', {'id': place.region.id}) }}">
                    <span class="icon-ar icon-ar-inverse icon-ar-circle">
                        <i class="glyphicon glyphicon-plus" aria-hidden="true"></i>
                    </span>
                </a>
                <a href="{{ path('admin-locality-toggle-lock-place', {'id': place.id}) }}">
                    <span class="icon-ar icon-ar-inverse icon-ar-circle">
                        {% if place.isLocked %}
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        {% else %}
                            <i class="fa fa-unlock" aria-hidden="true"></i>
                        {% endif %}
                    </span>
                </a>
            {% endif %}

            <ol class="breadcrumb pull-right">
                <li>
                    <a href="{{ url('locality-state-area', {'stateArea': place.region.stateArea.urlKey }) }}">{{ place.region.stateArea.name }}</a>
                </li>
                <li>
                    <a href="{{ url('locality-region', {'regionId': place.region.id }) }}">{{ place.region.name }}</a>
                </li>
                <li class="active">{{ place.name|raw }}</li>
            </ol>
        </div>
    </header>
{% endblock %}


{% block body %}
    <section>
        <div data-editable data-name="name">
            <h2 class="page-header no-margin-top">{{ place.name }}</h2>
        </div>

        <div data-editable data-name="text">
            {{ place.text|raw }}
        </div>
    </section>
{% endblock %}

{% block sidebar %}
    <div class="block animated fadeInDown animation-delay-10">
        <ul class="nav nav-tabs nav-tabs-ar" id="myTab2">
            <li class="active"><a href="#categories" data-toggle="tab"><i class="fa fa-folder-open"></i></a></li>
            {#<li><a href="#tags" data-toggle="tab"><i class="fa fa-tags"></i></a></li>#}
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="categories">
                <h3 class="post-title no-margin-top">Stolice (Župy)</h3>
                <ul class="simple">
                    {% for globalRegion in place.region.stateArea.regions %}
                        <li>
                            <a href="{{ url('locality-region', {'regionId': globalRegion.id }) }}">{{ globalRegion.name }}</a>
                            {% if globalRegion.id == place.region.id %}
                                <ul>
                                    {% for globalPlace in globalRegion.places %}
                                        <li>
                                            <a {% if globalPlace.id == place.id %}class="active"{% endif %}
                                               href="{{ url('locality-place', {'id': globalPlace.id}) }}">
                                                {% if globalPlace.id == place.id %}
                                                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                                                {% endif %}
                                                {% if globalPlace.isLocked %}
                                                    <i class="fa fa-lock" aria-hidden="true"></i>
                                                {% endif %}
                                                {{ globalPlace.name|raw }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>

            {#<div class="tab-pane" id="tags">#}
            {#<h3 class="post-title">Tags</h3>#}
            {#<div class="tags-cloud">#}
            {#<a href="#" class="tag">Web</a>#}
            {#<a href="#" class="tag">Artificial Intelligence</a>#}
            {#<a href="#" class="tag">Programing</a>#}
            {#<a href="#" class="tag">Design</a>#}
            {#<a href="#" class="tag">3D</a>#}
            {#<a href="#" class="tag">Games</a>#}
            {#<a href="#" class="tag">Resources</a>#}
            {#<a href="#" class="tag">2D</a>#}
            {#<a href="#" class="tag">C++</a>#}
            {#<a href="#" class="tag">Jquery</a>#}
            {#<a href="#" class="tag">Javascript</a>#}
            {#<a href="#" class="tag">Library</a>#}
            {#<a href="#" class="tag">Windows</a>#}
            {#<a href="#" class="tag">Linux</a>#}
            {#<a href="#" class="tag">Cloud</a>#}
            {#<a href="#" class="tag">Game developer</a>#}
            {#<a href="#" class="tag">Server</a>#}
            {#<a href="#" class="tag">Google</a>#}
            {#<a href="#" class="tag">Bootstrap</a>#}
            {#<a href="#" class="tag">Less</a>#}
            {#<a href="#" class="tag">Sass</a>#}
            {#<a href="#" class="tag">Engine</a>#}
            {#<a href="#" class="tag">Node.js</a>#}
            {#</div>#}
            {#</div>#}
        </div> <!-- tab-content -->
    </div>
{% endblock %}
{% block javascript %}
    {% if is_granted("ROLE_ADMIN") %}
        <script type="text/javascript">
            editUrl = "{{ path('admin-locality-place-update', {'placeId': place.id }) }}";
        </script>
        <script type="text/javascript" src="{{ asset('bundles/curtistemplate/js/editor/editor-place.js') }}"></script>
    {% endif %}
{% endblock %}

src/Curtis/AppBundle/Resources/views/Locality/region.html.twig
{% extends '@CurtisTemplate/Layout/base-left-side.html.twig' %}

{% block breadcrumbs %}
    <header class="main-header">
        <div class="container">
            <h1 class="page-title">Lokality</h1>

            <ol class="breadcrumb pull-right">
                <li>
                    <a href="{{ url('locality-state-area', {'stateArea': region.stateArea.urlKey }) }}">{{ region.stateArea.name }}</a>
                </li>
                <li class="active">{{ region.name }}</li>
            </ol>
        </div>
    </header>
{% endblock %}


{% block body %}
    {% for innerPlace in region.unlockedPlaces %}
        {% if loop.index % 2 == 0 %}
            {% set box_type = 'primary' %}
            {% set button_type = 'default' %}
        {% else %}
            {% set box_type = 'default' %}
            {% set button_type = 'primary' %}
        {% endif %}
        <div class="content-box box-{{ box_type }}">
            <div class="row">
                <div class="col-md-4">
                    <img src="{{ asset('bundles/curtisapp/img/kosihy.jpg') }}" alt="" class="img-responsive">
                </div>
                <div class="col-md-8">
                    <h4 class="content-box-title">{{ innerPlace.name }}</h4>
                    <p>{{ innerPlace.description }}</p>
                    <a href="{{ url('locality-place', {'placeId': innerPlace.id}) }}"
                       class="btn btn-ar btn-{{ button_type }}">Čítať viac</a>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block sidebar %}
    <div class="block animated fadeInDown animation-delay-10">
        <ul class="nav nav-tabs nav-tabs-ar" id="myTab2">
            <li class="active"><a href="#categories" data-toggle="tab"><i class="fa fa-folder-open"></i></a></li>
            {#<li><a href="#tags" data-toggle="tab"><i class="fa fa-tags"></i></a></li>#}
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="categories">
                <h3 class="post-title no-margin-top">Stolice (Župy)</h3>
                <ul class="simple">
                    {% for globalRegion in region.stateArea.regions %}
                        <li>
                            <a href="{{ url('locality-region', {'regionId': globalRegion.id }) }}">{{ globalRegion.name }}</a>
                            {% if globalRegion.id == region.id %}
                                <ul>
                                    {% for globalPlace in globalRegion.places %}
                                        <li>
                                            <a href="{{ url('locality-place', {'placeId': globalPlace.id}) }}">
                                                {% if globalPlace.isLocked %}
                                                    <i class="fa fa-lock" aria-hidden="true"></i>
                                                {% endif %}
                                                {{ globalPlace.name }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>

            {#<div class="tab-pane" id="tags">#}
            {#<h3 class="post-title">Tags</h3>#}
            {#<div class="tags-cloud">#}
            {#<a href="#" class="tag">Web</a>#}
            {#<a href="#" class="tag">Artificial Intelligence</a>#}
            {#<a href="#" class="tag">Programing</a>#}
            {#<a href="#" class="tag">Design</a>#}
            {#<a href="#" class="tag">3D</a>#}
            {#<a href="#" class="tag">Games</a>#}
            {#<a href="#" class="tag">Resources</a>#}
            {#<a href="#" class="tag">2D</a>#}
            {#<a href="#" class="tag">C++</a>#}
            {#<a href="#" class="tag">Jquery</a>#}
            {#<a href="#" class="tag">Javascript</a>#}
            {#<a href="#" class="tag">Library</a>#}
            {#<a href="#" class="tag">Windows</a>#}
            {#<a href="#" class="tag">Linux</a>#}
            {#<a href="#" class="tag">Cloud</a>#}
            {#<a href="#" class="tag">Game developer</a>#}
            {#<a href="#" class="tag">Server</a>#}
            {#<a href="#" class="tag">Google</a>#}
            {#<a href="#" class="tag">Bootstrap</a>#}
            {#<a href="#" class="tag">Less</a>#}
            {#<a href="#" class="tag">Sass</a>#}
            {#<a href="#" class="tag">Engine</a>#}
            {#<a href="#" class="tag">Node.js</a>#}
            {#</div>#}
            {#</div>#}
        </div> <!-- tab-content -->
    </div>
{% endblock %}

src/Curtis/AppBundle/Resources/views/Locality/state-area.html.twig
{% extends '@CurtisTemplate/Layout/base-left-side.html.twig' %}

{% block breadcrumbs %}
    <header class="main-header">
        <div class="container">
            <h1 class="page-title">Lokality</h1>

            <ol class="breadcrumb pull-right">
                {#<li><a href="#"></a></li>#}
                <li class="active">{{ stateArea.name }}</li>
            </ol>
        </div>
    </header>
{% endblock %}


{% block body %}
    <section class="animated fadeInRight animation-delay-10">
        <img class="img-responsive" src="{{ asset('bundles/curtisapp/img/locality-fullmap.png') }}"/>
    </section>
{% endblock %}

{% block sidebar %}
    <div class="block animated fadeInDown animation-delay-10">
        <ul class="nav nav-tabs nav-tabs-ar" id="myTab2">
            <li class="active"><a href="#categories" data-toggle="tab"><i class="fa fa-folder-open"></i></a></li>
            {#<li><a href="#tags" data-toggle="tab"><i class="fa fa-tags"></i></a></li>#}
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="categories">
                <h3 class="post-title no-margin-top">Stolice (Župy)</h3>
                <ul class="simple">
                    {% for region in stateArea.regions %}
                        <li><a href="{{ url('locality-region', {'regionId': region.id }) }}">{{ region.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>

            {#<div class="tab-pane" id="tags">#}
            {#<h3 class="post-title">Tags</h3>#}
            {#<div class="tags-cloud">#}
            {#<a href="#" class="tag">Web</a>#}
            {#<a href="#" class="tag">Artificial Intelligence</a>#}
            {#<a href="#" class="tag">Programing</a>#}
            {#<a href="#" class="tag">Design</a>#}
            {#<a href="#" class="tag">3D</a>#}
            {#<a href="#" class="tag">Games</a>#}
            {#<a href="#" class="tag">Resources</a>#}
            {#<a href="#" class="tag">2D</a>#}
            {#<a href="#" class="tag">C++</a>#}
            {#<a href="#" class="tag">Jquery</a>#}
            {#<a href="#" class="tag">Javascript</a>#}
            {#<a href="#" class="tag">Library</a>#}
            {#<a href="#" class="tag">Windows</a>#}
            {#<a href="#" class="tag">Linux</a>#}
            {#<a href="#" class="tag">Cloud</a>#}
            {#<a href="#" class="tag">Game developer</a>#}
            {#<a href="#" class="tag">Server</a>#}
            {#<a href="#" class="tag">Google</a>#}
            {#<a href="#" class="tag">Bootstrap</a>#}
            {#<a href="#" class="tag">Less</a>#}
            {#<a href="#" class="tag">Sass</a>#}
            {#<a href="#" class="tag">Engine</a>#}
            {#<a href="#" class="tag">Node.js</a>#}
            {#</div>#}
            {#</div>#}
        </div> <!-- tab-content -->
    </div>
{% endblock %}